require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

# Disable inline documentation since it is not practical or desired
# to add it to every class and module.
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 24

RSpec/MultipleExpectations:
  Max: 3
